spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: "localhost:9092" #kafka server
                    zkNodes: "localhost:2181" #zookeeper server
                    headers:
                        - X-B3-TraceId
                        - X-B3-SpanId
                        - X-B3-Sampled
                        - X-B3-ParentSpanId
                        - X-Span-Name
                        - X-Process-Id
                        - spanId
                        - spanSampled
                        - spanProcessId
                        - spanParentSpanId
                        - spanTraceId
                        - spanName
                        - messageSent
